baseURL: https://mkiruba.github.io/
languageCode: en-us
title: "Kiru's Blog"

module:
  imports:
  - path: github.com/hugo-toha/toha/v4
  mounts:
  - source: static/files
    target: static/files
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts

languages:
  en:
    languageName: English
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - RSS
    - JSON

enableEmoji: true

params:
  gitRepo: https://github.com/mkiruba/kiru.github.io
  features:
    portfolio:
      enable: true
    blog:
      enable: false
    toc:
      enable: false
  footer:
    enable: true 